### ISSUE TITLE
Domain redirect + no SSL

### ISSUE THREAD

**Issue by erik-praznovsky** [DerTyp7/ts5-obs-overlay#102]
> Screenshots are welcome
## Describe the bug
URL https://dertyp7.github.io/ts5-obs-overlay/ is automatically redirecting to https://www.janis-meister.com/ts5-obs-overlay/
New ULR dont have valid SSL certificate - plugin not working in OBS. 
Many thx for fix!
Erik

**Do you use the local or online version?**
- [x] Online version with URL: `https://dertyp7.github.io/ts5-obs-overlay`
- [ ] The version named below locally downloaded on my device

**Comment by DerTyp7** [comment]
Thanks for your report. 
I'm already on it. 
I'm having some trouble with GitHub pages and the DNS, but should be fixed soon

**Comment by DerTyp7** [comment]
The issue has been fixed.

The new generator URL is: [https://dertyp7.tealfire.de/#/generate](https://dertyp7.tealfire.de/#/generate)

**If your browser keeps sending you to the old URL**, blame the cache. 
Quick fix: hop into an Incognito/Private Tab. Your browser should sort out the cache on its own over time.
