### ISSUE TITLE
Clients are not displayed | Clients werden nicht angezeigt

### ISSUE THREAD

**Issue by Hoerli1337** [DerTyp7/ts5-obs-overlay#26]
Hi!

The clients are not displayed for me.
I have included the HTML page in OBS according to the instructions, but the browser window remains empty.
If I open the HTML page in a normal browser, I can see the accesses and updates via the developer options.
However, there the page also remains completely empty.
_______________
Die Clients werden bei mir nicht angezeigt.
Habe die HTML-Seite nach der Anleitung in OBS eingebunden, aber das Browserfenster bleibt leer.
Wenn ich die HTML-Seite in einem normalen Browser öffne, sehe ich über die Entwickleroptionen die Zugriffe und aktualisierungen.
Dort bleibt jedoch die Seite auch komplett leer.
_______________
- Windows 10
- OBS 29.1.3
- Firefox 114.0.1

![Setup](https://github.com/DerTyp7/ts5-obs-overlay/assets/13108516/5e4179a0-630b-469f-b248-993d03d861b7)
![Konsole](https://github.com/DerTyp7/ts5-obs-overlay/assets/13108516/3b1a0754-3db8-470f-98d7-6d272496197f)

**Comment by DerTyp7** [comment]
Could you try to add `file://` to your path and use a forward slash instead of a backslash, like this: `file://G:/Users/...` ?
After you changed this, press the refresh button in OBS. 
![image](https://github.com/DerTyp7/ts5-obs-overlay/assets/76851529/3be6f5e3-6dc6-438b-8424-1730458d4574)

Wait 30-40 seconds, because the overlay clears the API-Key in the local storage after a few failed reconnects.

**Comment by DerTyp7** [comment]
Based on your screenshot of the console, I think you're using an old version of the overlay.

I have just noticed that the URL in the readme was wrong. It pointed to an old release.

thats the latest release: https://github.com/DerTyp7/ts5-obs-overlay/releases/latest

**Comment by Hoerli1337** [comment]
Ah cool, with the latest version it works.
I don't know what GitHub made available as a download.
I didn't even have to specify `file://`. With the normal path it worked directly.
