### ISSUE TITLE
Overlay list / resolution & scaling

### ISSUE THREAD

**Issue by zatroch** [DerTyp7/ts5-obs-overlay#77]
## Describe the bug
Overlay always shows just FOUR nicknames listed no matter what resolution or scaling is used. Even when I drag/resize the box on scene manually. My screen/desktop resolution is full HD and output stream from OBS is 720p.

![obrázok_2023-10-21_113504565](https://github.com/DerTyp7/ts5-obs-overlay/assets/86196715/270b40fc-47f0-4e6f-bee9-127939d21c93)

## To Reproduce
Proper setup either with 1920x1080 or 1280x720 resolution in "browser layer options".

## Expected behavior
I expect the list to show all the members of the channel/room with at least greyed-out dots.

**Your environment:**
 - OS: Windows 11
 - OBS version: 29.1.3
 - Overlay version v1.3.1

**Comment by DerTyp7** [comment]
I think I could reproduce the problem. Can you try setting the size to something like 1920x2000px, so it fills up the space to your bottom.

I think the issue is that the ratio need to be more like 1:2 instead of 16:9.

**Comment by zatroch** [comment]
Thanks for the x2000 tip, much better now. (=

**Comment by DerTyp7** [comment]
No problem. I am going to update the instruction page accordingly
